version: '3'
services:
  web:
    # replace username/repo:tag with your name and image details
    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      - .:/questionnaire

    ports:
      - '8000:8000'

    command: ./entrypoint.sh
