# Generated by Django 2.0.9 on 2019-01-04 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0002_questionchoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choices',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('choice', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='choice_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='questionnaire.Choices'),
        ),
        migrations.AddField(
            model_name='questionchoice',
            name='choice_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='questionnaire.Choices'),
        ),
        migrations.RemoveField(
            model_name='answer',
            name='answer',
        ),
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together={('question_id', 'choice_id')},
        ),
        migrations.RemoveField(
            model_name='questionchoice',
            name='choice',
        ),
        migrations.AlterUniqueTogether(
            name='questionchoice',
            unique_together={('question_id', 'choice_id')},
        ),
    ]
