# Generated by Django 2.0.9 on 2019-01-04 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0003_auto_20190104_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='choice_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='questionnaire.Choices'),
        ),
        migrations.AlterField(
            model_name='questionchoice',
            name='choice_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='questionnaire.Choices'),
        ),
    ]
