# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  checkout_code:
    working_directory: ~/questionnaire
    docker:
      - image: circleci/python:3.7.1
    steps:
      - checkout
      - persist_to_workspace:
          root: .
          paths: .

  install_dependencies:
    working_directory: ~
    docker:
      - image: circleci/python:3.7.1
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Install Dependencies
          command: pip install -r requirements.txt

  run_test:
    working_directory: ~/questionnaire
    docker:
      - image: circleci/python:3.7.1
      - image: circleci/postgres:11.1-alpine-ram
    steps:
      - attach_workspace:
          at: .
      - run:
          name: run test
          command: python manage.py test

workflows:
  version: 2
  simplezat_pipeline:
    jobs:
      - checkout_code
      - install_dependencies:
          requires:
            - checkout_code
      - run_test:
          requires:
            - install_dependencies
