# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  checkout_code:
    working_directory: ~/questionnaire
    docker:
      - image: python:3.6
    steps:
      - checkout
      - persist_to_workspace:
          root: .
          paths: .

  install_dependencies:
    working_directory: ~/questionnaire
    docker:
      - image: python:3.6
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Install Dependencies
          command: pip install -r requirements.txt

  run_test:
    working_directory: ~/questionnaire
    docker:
      - image: python:3.6
      - image: postgres
    steps:
      - attach_workspace:
          at: .
      - run:
          name: run test
          command: |
            pip install -r requirements.txt
            cd questionnaire
            export DATABASE_HOST=localhost
            python manage.py test

  build_docker_image:
    working_directory: ~/questionnaire
    docker:
      - image: circleci/python:3.7.1
    steps:
      - attach_workspace:
          at: .
      - setup_remote_docker
      - run:
          name: build docker image
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
            docker build -t mixkungz/hello-django:stable .
            docker push mixkungz/hello-django:stable

  deploy:
    working_directory: ~/questionnaire
    docker:
      - image: circleci/python:3.7.1
    steps:
      - attach_workspace:
          at: .
      - add_ssh_keys
      - run:
          name: deploy
          command: |
            ssh-keyscan -H 35.198.253.178 >> ~/.ssh/known_hosts
            ssh pcr.mixkungz-circleci@35.198.253.178 sudo su && deploy.sh

workflows:
  version: 2
  simplezat_pipeline:
    jobs:
      - checkout_code
      - install_dependencies:
          requires:
            - checkout_code
      - run_test:
          requires:
            - install_dependencies
      - build_docker_image:
          requires:
            - run_test
      - deploy:
          requires:
            - build_docker_image
